#ifndef defines.h
#define defines.h

//INPUTS
        
    #define UP_PIN 1  //BOWTHRUSTER LEFT / R49
    #define DOWN_PIN 2  //BOWTHRUSTER RIGHT / R48
    #define EAST_PIN 3 //LEFT ENGINE FORWARD / R47
    #define WEST_PIN 4 //RIGHT ENGINE FORWARD / R46
    #define SOUTH_PIN 5 //LEFT ENGINE BACKWARD / R45
    #define NORTH_PIN 6 //RIGHT ENGINE BACKWARD / R44
    #define R1_PIN 7 //STERNTHRUSTER LEFT / R43
    #define R2_PIN 8 //STERNTHRUSTER RIGHT / R42
    #define R0_PIN 9 //HORN / R41


//OUTPUTS

    #define BOWTHRUSTER_LEFT_PIN 17
    #define BOWTHRUSTER_RIGHT_PIN 16
    
    #define LEFT_ENGINE_FORWARD_PIN 33
    #define LEFT_ENGINE_REVERSE_PIN 34
    #define LEFT_ENGINE_NEUTRAL_SWITCH_PIN 35
    
    #define RIGHT_ENGINE_FORWARD_PIN 20    
    #define RIGHT_ENGINE_REVERSE_PIN 21
    #define RIGHT_ENGINE_NEUTRAL_SWITCH_PIN 26
    
    #define STERNTHRUSTER_LEFT_PIN 15
    #define STERNTHRUSTER_RIGHT_PIN 14
    
    #define HORN_PIN 39



    #endif
    
